
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", path: "vagrant.install.sh"

  config.vm.synced_folder "../", "/var/www/html/perfectclick"
  config.vm.synced_folder "../../machine/install", "/install"

  config.vm.network "private_network", ip: "192.168.20.20"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "qe_perfectclick_vm"
  end

end
